import json
from typing import List, Dict, Any, Tuple
from pydantic import BaseModel, Field, field_validator
from ai.runtime import AIRuntime
from loguru import logger

class TaskNode(BaseModel):
    id: int
    action: str
    input: Dict[str, Any] = Field(default_factory=dict)
    max_retries: int = Field(default=0, ge=0)

class ExecutionGraph(BaseModel):
    nodes: List[TaskNode] = Field(default_factory=list)
    edges: List[Tuple[int, int]] = Field(default_factory=list)  # (from_id, to_id)

    @field_validator('edges')
    @classmethod
    def validate_graph(cls, v: List[Tuple[int, int]], info):
        # Проверка 1: Все ID в ребрах должны существовать в узлах
        node_ids = {node.id for node in info.data.get('nodes', [])}
        for src, dst in v:
            if src not in node_ids:
                raise ValueError(f"Edge refers to non-existent node ID: {src}")
            if dst not in node_ids:
                raise ValueError(f"Edge refers to non-existent node ID: {dst}")
        
        # Проверка 2: Отсутствие циклов (простой обход для DAG)
        if v:
            cls._check_cycles(node_ids, v)
        return v

    @classmethod
    def _check_cycles(cls, node_ids: set, edges: List[Tuple[int, int]]):
        adj = {node_id: [] for node_id in node_ids}
        for src, dst in edges:
            adj[src].append(dst)
        
        visited = set()
        path = set()

        def visit(u):
            if u in path: return True
            if u in visited: return False
            visited.add(u)
            path.add(u)
            for v in adj.get(u, []):
                if visit(v): return True
            path.remove(u)
            return False

        for node_id in node_ids:
            if visit(node_id):
                raise ValueError("Graph contains cycles (not a DAG)")

class ExecutionPlan(BaseModel):
    intent: str
    graph: ExecutionGraph = Field(default_factory=ExecutionGraph)
    risk_level: str = "low"
    requires_confirmation: bool = True

class KernelPlanner:
    """
    Планировщик DevOS Kernel.
    Использует ИИ для генерации и валидации графа выполнения (DAG).
    """
    
    def __init__(self, runtime: AIRuntime = None):
        self.runtime = runtime or AIRuntime()

    async def plan(self, intent: str, feedback_context: Dict[str, Any] = None) -> ExecutionPlan:
        """
        Преобразует интент пользователя в структурированный граф задач с учетом опционального feedback_context.
        """
        logger.info(f"Planning execution for intent: {intent}")
        try:
            # 1. Получение структурированного ответа от ИИ
            # Инжектируем feedback_context как дополнительный структурированный аргумент (если поддерживается рантаймом)
            # Либо сериализуем его в JSON и добавляем к вводу, если рантайм принимает только строку.
            # Для сохранения чистоты архитектуры передаем его в user_input в виде JSON-структуры.
            
            payload = {"intent": intent}
            if feedback_context:
                payload["advisory_feedback"] = feedback_context
                
            raw_response = await self.runtime.execute_structured(
                prompt_name="DEVOS KERNEL PROMPT", 
                user_input=json.dumps(payload, ensure_ascii=False) if feedback_context else intent
            )
            
            # 2. Валидация и конвертация через Pydantic
            # Pydantic автоматически проверит структуру и вызовет validate_graph для DAG
            plan = ExecutionPlan(**raw_response)
            
            logger.success(f"Generated plan with {len(plan.graph.nodes)} nodes and {len(plan.graph.edges)} edges.")
            return plan

        except ValidationError as ve:
            logger.error(f"AI generated an invalid graph: {ve}")
            raise ValueError(f"Invalid execution graph generated by AI: {ve}")
        except Exception as e:
            logger.error(f"Planning process failed: {e}")
            raise
